# main
im_dim_x: 512                 # Image width.
im_dim_y: 512                 # Image height.
data_file: ./data/3c353/data_3c353.mat # Path to the input .mat data file.
output_path: ./results/       # Path to the final fits files.

# measurement operator
super_resolution: 1.5         # Super resolution factor.
save_all_outputs: False        # (optional) Save all intermediate outputs, otherwise only final iteration results will be saved.
imweight_name: nWimag         # Name of variable containing weighting in the uv file.
natural_weight: True

# algorithm
series: R2D2                  # Incarnation of the R2D2 algorithm: "R2D2" or "R3D3".
num_iter: 15                  # Number of DNNs in the R2D2/R3D3 series
layers: 1                     # Number of network layers in the DNN architecture. Currently acceptable values 1, 3, 6.
ckpt_path: ./ckpt/R2D2        # Path to the directory of the DNN checkpoints.
res_on_gpu: True              # (optional) Compute residual dirty images on GPU to significantly accelerate overall imaging time.
operator_type: table          # (optional) choose from [table, sparse_matrix], 'table' is faster, 'sparse_matrix' is relatively more accurate.

# simulations
gdth_file: ./data/3c353/3c353_GTfits.fits # (optional) Path to the ground truth fits file.
target_dynamic_range:         # (optional) Target dynamic range for computation of logSNR metric, default None.

# miscellaneous
cpus: 1                       # (optional) Number of cpu to be used for computing residual dirty images when `res_on_gpu` is False
verbose: 1                    # Choose between 1 and 0